[package]
name = "visualisation-sim"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.32.2"
egui = "0.32.2"
embedded-graphics = "0.8.1"
rand = "0.9.2"
visualisation = { path = "../visualisation" }
