[package]
name = "visualisation"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-graphics = "0.8.1"
embassy-time = { version = "0.4.0", features = ["defmt", "defmt-timestamp-uptime"] }
libm = "0.2.15"
